/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Car.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Car.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_6001.geometry} material={materials['M_chevy_impala_01_B_inst.001']} position={[-70.49, -93.654, -8.661]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.M_scratched_glass_seamless_inst} />
      <mesh geometry={nodes.Object_12001.geometry} material={materials['M_chevy_impala_01_A_inst.001']} position={[-49.534, -82.448, -8.688]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-92.93, 5.44, 79.394]} rotation={[-3.132, -1.54, -Math.PI / 2]} scale={[5.547, 1.037, 17.597]} />
    </group>
  )
}

useGLTF.preload('/Car.glb')
